### ISSUE TITLE
Some combos are broken, but not all of them

### ISSUE THREAD

**Issue by freakachu** [PrincessRTFM/XIVComboPlugin#7] opened 2021-12-20 15:49 UTC
after the most recent update, it seems PLD and MNK combos specifically are not functioning. I uninstalled/reinstalled the plugin, double checked that the combos are enabled in the settings, tried disabling and re-enabling them, nothing worked. RPR worked correctly, so I know the plugin is loaded and functional.

combos not working are:
goring blade
royal authority
atonement feature
prominence
requiescat feature
requiescat confiteor

none of the MNK aoe balance features appear to work either. it's a sad day for me as I main PLD and am leveling MNK lol

**Comment by PrincessRTFM** [comment] 2021-12-27 04:12
This is weird, because one of my friends says that Royal Authority, Atonement, and Prominence are all working, though she can't get Requiescat to "do the thing" either. I just sent someone on discord who had similar MNK issues a debug build, but it's really late at night and I can't for the _life_ of me figure out what's going on - some of the replacers just don't seem to be running at all, and I can't find a reason for it.

If you want to help too and you know how to set up "dev" (local) plugins in dalamud, please _disable all XIVCombo forks and versions_, then unzip [this debug build](https://github.com/PrincessRTFM/XIVComboPlugin/files/7778267/XIVComboVX.zip) and load the included DLL as a dev plugin, preferably on a fresh game launch, switch to MNK with Rockbreaker on a hotbar somewhere, wait about twenty seconds or so, then unload the plugin and send me your `%AppData%\XIVLauncher\dalamud.log` file.

Please note that this won't fix the problem. I can't even tell where the problem _is_ yet. This is _purely_ to help me track down what exactly is going wrong right now. While this build _technically_ has neither new nor missing features, the performance may be worse and it's not _meant_ to be run for normal play. You'll be able to tell that the debug build is loaded because the dalamud dev menu will be toggled at the top of your screen.

**Comment by PrincessRTFM** [comment] 2021-12-27 15:14
Disregard that debug build and the instructions.

I've just confirmed with another friend via video that the 1-2-3 Royal Authority combo is working for them at level 56. Another friend confirmed by text that Royal Authority, Atonement, and Prominence are all working. Can you unload the plugin, delete (or move) your configuration file (`%AppData%\XIVLauncher\pluginConfigs\XIVComboVX.json`), load the plugin again, turn the combos on, and report back?

**Comment by PrincessRTFM** [comment] 2021-12-27 23:50
@AwesomeJames2120 You were having issues with DRG, can you load the official build, update your plugins with the `/xlplugins` button, then tell me if there's any change? If there isn't, can you _re-assign_ the broken actions on your hotbars from the actions window?

<details>
<summary>Explanation</summary>

One person helping me live debug had a problem with monk's Rockbreaker not updating _until_ they replaced it on their hotbar, and according to the debug build I sent them, the plugin didn't detect Rockbreaker at all. I'm wondering if perhaps the action ID changed so that it's technically a different button.

Another person doing the same says that paladin's Confiteor _was_ failing to update, but after I made a few adjustments to some internals, it's working now, so it may also have been something with that.

</details>

**Comment by PrincessRTFM** [comment] 2021-12-28 00:40
Issue title updated because reports included RPR, MNK, DRG, and PLD. It _seems_ to be fixed, from what I can tell and the people I've been able to contact. I'm leaving this open for a little longer so AwesomeJames can respond, but if they have no issues (or don't respond for a while) then I'll tentatively declare this fixed and close the issue.

**Comment by AwesomeJames2120** [comment] 2021-12-28 05:56
Since i have everything unlocked to at least level 80 (with Pld, Sch, Sge, Smn at 90, reaper at 86), i went about testing all of them

Prefered additions:
Sage - A phlegma into Dyskrasia option when its out of stacks would be great
Reaper - Only thing it needs is an automatic switch to Gluttony if its off cooldown

Jobs with issues

Summoner - Both tri-disaster  *and* ruin become x rite, when tri-disaster should become x Catastrophe instead
Bard - Truthfully i have no idea how new bard works, but when all the options are enabled, hitting Rain of death and Bloodletter becomes much harder since they get replaced even when they have charges

Otherwise, every other job works fine (at least at level 80)

**Comment by PrincessRTFM** [comment] 2021-12-28 08:03
Since the replacers are functioning, I'm closing this issue, but I'll open a new one about the requests and the weird behaviour momentarily.

**Closed by PrincessRTFM** 2021-12-28 08:03 UTC
